[package]
name = "actix-web-learn"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = "1"
serde_json = "1"
futures = "0.3"
derive_more = "2"
actix-multipart = "0.7"
tokio = "1"
